[package]
name = "jyd2d"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/andete/jyd2d"

[dependencies]
assert_approx_eq = "1.1.0"
